### PR TITLE
Added a helpful link to codenewbie

### PR DESCRIPTION
**Pull request by Myles2**
Also got rid of "<3" that was in front of a closing </h2> tag.

### CODE REVIEW

**Comment by richie-south** [comment]
Hey this is just my fork checkout the real project 😃 https://github.com/lingonsaft/hacktoberfest

**Comment by Myles2** [comment]
@richie-south haha I ended up realizing that after I had finished lol. Is there something in particular I can contribute to the page? This is my first time contributing to an open source project.

**Comment by richie-south** [comment]
@Myles2 Hey that's great! :D :D 

We constantly have lots of breaking on the page 😛(here is the live example https://hacktoberfest.lingonsaft.com) so just browse and you will probably find something

You can also checkout the issues https://github.com/lingonsaft/hacktoberfest/issues for something to do. 

But one of the easiest for a beginner to add is to add a helpfull link on the "helpful-material" page https://hacktoberfest.lingonsaft.com/helpful-material

**Comment by Myles2** [comment]
Okay, sounds good. Happy Hacking!😆

**Pull request closed without merging**
